backend:
  name: github
  repo: imsxx/imsxx-hugo
  branch: main

editorial_workflow: true
media_folder: static/images/uploads
public_folder: /images/uploads

site_url: https://imsxx.com
locale: zh_Hans

collections:
  - name: "blog"
    label: "博客文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "作者", name: "author", widget: "string", default: "梦随乡兮"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "URL别名", name: "slug", widget: "string", required: false}
      - {label: "分类", name: "categories", widget: "list", required: false}
      - {label: "标签", name: "tags", widget: "list", required: false}
      - {label: "摘要", name: "description", widget: "text", required: false}
      - {label: "特色图片", name: "image", widget: "image", required: false}
      - {label: "草稿", name: "draft", widget: "boolean", default: false}
      - {label: "正文", name: "body", widget: "markdown"}

  - name: "pages"
    label: "页面"
    files:
      - label: "关于页面"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "发布日期", name: "date", widget: "datetime"}
          - {label: "正文", name: "body", widget: "markdown"}

editor:
  preview: true

search: true

media_library:
  name: git
  repo: imsxx/imsxx-hugo
  branch: main